import type { FoodProfile } from "./types";

// Πλήρες Level-2 canonical dish dataset — Food Taxonomy v2 (44 εγκεκριμένα
// dishes) + bakaliaros-skordalia (1 επιπλέον, ξεχωριστά εγκεκριμένο entry
// κατά το Final Scoring Model Approval Pass). Σύνολο: 45.
//
// ΚΑΘΕ τιμή εδώ (slug/name/category/salt/fat/spice/sweet) προέρχεται
// αυστηρά από το ήδη εγκεκριμένο "55 PROPOSED DISHES + FOOD PROFILE TABLE"
// (Food-Side Model v1) διαμορφωμένο σύμφωνα με τις αποφάσεις του Food
// Taxonomy Review v2 — 8 dishes αφαιρέθηκαν, 3 έγιναν umbrella-only
// (game-meat/cured-meats/mezedes-mix, ΔΕΝ εμφανίζονται εδώ σκόπιμα), 3
// poultry entries ενοποιήθηκαν σε ένα ("chicken"), 2 ακονίστηκαν σε πιο
// συγκεκριμένο πιάτο (eggplant-dishes→melitzanosalata, legumes→fakes) — οι
// αριθμητικές τιμές τους παρέμειναν ίδιες, ακριβώς όπως ενέκρινε το v2
// review ("no other numeric contradictions found"). Καμία τιμή δεν είναι
// νέα/επινοημένη σε αυτό το pass.
//
// Οι slugs `moussaka` και `chocolate-dessert` είναι οι επίσημα εγκεκριμένοι
// (όχι `mousakas`/`glyko-sokolatas` που είχαν χρησιμοποιηθεί προσωρινά στο
// αρχικό 6-dish test set πριν ανακτηθεί το πλήρες, εγκεκριμένο taxonomy).
//
// seoTitle/seoDescription: δημόσιο, public-facing copy — ξεχωριστό από το
// editorialSanityCheck (που παραμένει ΜΟΝΟ εσωτερικό review metadata, ποτέ
// SEO fallback, ποτέ UI explanation, ποτέ scoring input). Προστέθηκαν σε
// αυτό το SEO cleanup pass, χωρίς καμία αλλαγή στις αριθμητικές τιμές.

export const FOOD_PROFILES: FoodProfile[] = [
  // ── Ψάρι & θαλασσινά (9) ──────────────────────────────────────────────
  {
    slug: "sushi",
    name: "Σούσι",
    categorySlug: "seafood",
    saltiness: 2,
    fattiness: 1,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Ωμό ψάρι/ρύζι με ξίδι — χρειάζεται κρασί υψηλής οξύτητας, φρεσκάδα, ελαφρύ σώμα.",
    seoTitle: "Σούσι & κρασί | Oenia",
    seoDescription: "Ελληνικά λευκά και ροζέ κρασιά με ζωντανή οξύτητα, ιδανικά για σούσι — δες προτάσεις ταιριάσματος από την Oenia.",
  },
  {
    slug: "sashimi",
    name: "Σασίμι",
    categorySlug: "seafood",
    saltiness: 1,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Καθαρό, ωμό ψάρι χωρίς ρύζι — χρειάζεται υψηλή οξύτητα και καθαρό, μη επιθετικό χαρακτήρα.",
    seoTitle: "Σασίμι & κρασί | Oenia",
    seoDescription: "Ωμό ψάρι θέλει καθαρό, δροσερό κρασί. Ανακάλυψε ελληνικά λευκά με υψηλή οξύτητα που ταιριάζουν με σασίμι.",
  },
  {
    slug: "grilled-fish",
    name: "Ψητό ψάρι",
    categorySlug: "seafood",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Απλό ψητό ψάρι — αρκεί μέτρια οξύτητα και ελαφρύ έως μεσαίο σώμα.",
    seoTitle: "Ψητό ψάρι & κρασί | Oenia",
    seoDescription: "Ελαφριά έως μεσαία λευκά κρασιά για ψητό ψάρι — προτάσεις ταιριάσματος βασισμένες σε πραγματικά δεδομένα κρασιού.",
  },
  {
    slug: "grilled-salmon",
    name: "Ψητός σολομός",
    categorySlug: "seafood",
    saltiness: 2,
    fattiness: 4,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Λιπαρό ψάρι — χρειάζεται καλή οξύτητα ώστε να «κόψει» το λίπος του σολομού.",
    seoTitle: "Ψητός σολομός & κρασί | Oenia",
    seoDescription: "Ο σολομός θέλει κρασί με καλή οξύτητα που εξισορροπεί το λίπος του. Δες ποια ελληνικά λευκά ταιριάζουν.",
  },
  {
    slug: "fried-calamari",
    name: "Τηγανητό καλαμάρι",
    categorySlug: "seafood",
    saltiness: 3,
    fattiness: 4,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Τηγανητό, λιπαρό — χρειάζεται υψηλή οξύτητα, όπως κάθε τηγανητό πιάτο.",
    seoTitle: "Τηγανητό καλαμάρι & κρασί | Oenia",
    seoDescription: "Τηγανητά θαλασσινά χρειάζονται κρασί με έντονη οξύτητα. Ανακάλυψε ποια ελληνικά λευκά ταιριάζουν με καλαμάρι.",
  },
  {
    slug: "shrimp-saganaki",
    name: "Γαρίδες σαγανάκι",
    categorySlug: "seafood",
    saltiness: 3,
    fattiness: 3,
    spiciness: 1,
    sweetness: 1,
    editorialSanityCheck: "Γαρίδες με ντοματοσάλτσα/τυρί — χρειάζεται οξύτητα και φρεσκάδα να ισορροπήσουν το λίπος.",
    seoTitle: "Γαρίδες σαγανάκι & κρασί | Oenia",
    seoDescription: "Γαρίδες σε ντοματοσάλτσα με φέτα θέλουν κρασί με φρεσκάδα και οξύτητα — δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "oysters",
    name: "Στρείδια",
    categorySlug: "seafood",
    saltiness: 4,
    fattiness: 1,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Πολύ αλμυρά, ορυκτικά — χρειάζονται πολύ υψηλή οξύτητα και ορυκτικό χαρακτήρα στο κρασί.",
    seoTitle: "Στρείδια & κρασί | Oenia",
    seoDescription: "Τα στρείδια θέλουν κρασί με πολύ υψηλή οξύτητα και ορυκτικό χαρακτήρα. Ανακάλυψε ποια ελληνικά λευκά ταιριάζουν.",
  },
  {
    slug: "mussels",
    name: "Μύδια",
    categorySlug: "seafood",
    saltiness: 3,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Θαλασσινή αλμύρα — χρειάζεται οξύτητα και φρεσκάδα.",
    seoTitle: "Μύδια & κρασί | Oenia",
    seoDescription: "Θαλασσινή αλμύρα χρειάζεται φρέσκο, όξινο κρασί. Ανακάλυψε ελληνικά λευκά που ταιριάζουν με μύδια.",
  },
  {
    slug: "octopus-grilled",
    name: "Χταπόδι σχάρας",
    categorySlug: "seafood",
    saltiness: 3,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ψητό χταπόδι — οξύτητα με λίγη ανοχή σε ελαφριά τανίνη, λόγω της υφής στο ψήσιμο.",
    seoTitle: "Χταπόδι σχάρας & κρασί | Oenia",
    seoDescription: "Ψητό χταπόδι ταιριάζει με κρασιά υψηλής οξύτητας που αντέχουν και λίγη τανίνη. Δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "seafood-pasta",
    name: "Ζυμαρικά με θαλασσινά",
    categorySlug: "pasta", // v2: reclassified seafood→pasta, είναι ζυμαρικό πιάτο
    saltiness: 3,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ζυμαρικά με θαλασσινά — οξύτητα, ελαφρύ έως μεσαίο σώμα.",
    seoTitle: "Ζυμαρικά με θαλασσινά & κρασί | Oenia",
    seoDescription: "Ζυμαρικά με θαλασσινά θέλουν κρασί με οξύτητα και ελαφρύ έως μεσαίο σώμα — δες τι ταιριάζει.",
  },

  // ── Κόκκινο κρέας (7) ─────────────────────────────────────────────────
  {
    slug: "steak",
    name: "Μπριζόλα / Steak",
    categorySlug: "red-meat",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ψητό κόκκινο κρέας — θέλει δομή/τανίνη για να δέσει με το λίπος και την πρωτεΐνη.",
    seoTitle: "Μπριζόλα & κρασί | Oenia",
    seoDescription: "Ψητό κόκκινο κρέας θέλει κρασί με σώμα και τανίνη. Ανακάλυψε δομημένα ελληνικά ερυθρά για μπριζόλα.",
  },
  {
    slug: "lamb-roast",
    name: "Αρνί ψητό",
    categorySlug: "red-meat",
    saltiness: 2,
    fattiness: 4,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Λιπαρό ψητό αρνί — χρειάζεται σώμα, τανίνη και ωριμότητα στο κρασί.",
    seoTitle: "Αρνί ψητό & κρασί | Oenia",
    seoDescription: "Το ψητό αρνί ζητά κρασί με σώμα, τανίνη και ωριμότητα. Δες ποια ελληνικά ερυθρά ταιριάζουν.",
  },
  {
    slug: "lamb-chops",
    name: "Παϊδάκια",
    categorySlug: "red-meat",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Σχάρας αρνίσιο κρέας — σώμα και τανίνη, λίγο πιο ελαφρύ από το ψητό αρνί.",
    seoTitle: "Παϊδάκια & κρασί | Oenia",
    seoDescription: "Παϊδάκια σχάρας ταιριάζουν με δομημένα ερυθρά κρασιά. Δες προτάσεις ταιριάσματος από την Oenia.",
  },
  {
    slug: "burger",
    name: "Μπέργκερ",
    categorySlug: "red-meat",
    saltiness: 3,
    fattiness: 4,
    spiciness: 1,
    sweetness: 1,
    editorialSanityCheck: "Λιπαρό κιμαδένιο κρέας με σάλτσες — σώμα και τανίνη, με λίγη φρεσκάδα λόγω των συνοδευτικών.",
    seoTitle: "Μπέργκερ & κρασί | Oenia",
    seoDescription: "Λιπαρό κρέας με σάλτσες θέλει κρασί με σώμα και τανίνη, με λίγη φρεσκάδα. Ανακάλυψε τι ταιριάζει με μπέργκερ.",
  },
  {
    slug: "beef-stew",
    name: "Μοσχάρι κοκκινιστό",
    categorySlug: "red-meat",
    saltiness: 2,
    fattiness: 3,
    spiciness: 1,
    sweetness: 1,
    editorialSanityCheck: "Σιγοβρασμένο κόκκινο κρέας σε σάλτσα ντομάτας — σώμα και ώριμες, στρογγυλεμένες τανίνες.",
    seoTitle: "Μοσχάρι κοκκινιστό & κρασί | Oenia",
    seoDescription: "Το κοκκινιστό σε σάλτσα ντομάτας θέλει κρασί με σώμα και στρογγυλεμένες τανίνες — δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "bbq-ribs",
    name: "Χοιρινά πλευρά BBQ",
    categorySlug: "red-meat",
    saltiness: 3,
    fattiness: 5,
    spiciness: 2,
    sweetness: 2,
    editorialSanityCheck: "Πολύ λιπαρό, γλυκόξινο BBQ — χρειάζεται σώμα και τανίνη, με ανοχή ή και λίγη γλύκα στο κρασί.",
    seoTitle: "Χοιρινά πλευρά BBQ & κρασί | Oenia",
    seoDescription: "Λιπαρό, γλυκόξινο BBQ χρειάζεται κρασί με σώμα και τανίνη που αντέχει λίγη γλύκα. Δες τι ταιριάζει.",
  },
  {
    slug: "moussaka",
    name: "Μουσακάς",
    categorySlug: "red-meat",
    saltiness: 2,
    fattiness: 4,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Κιμάς + μπεσαμέλ + ντομάτα — χρειάζεται και δομή (κρέας) και πραγματική οξύτητα (ντομάτα), όχι μόνο το ένα.",
    seoTitle: "Μουσακάς & κρασί | Oenia",
    seoDescription: "Ο μουσακάς θέλει κρασί με δομή για το κρέας αλλά και οξύτητα για την ντομάτα. Δες ελληνικά ερυθρά που ταιριάζουν.",
  },

  // ── Λευκό κρέας & πουλερικά (4) ───────────────────────────────────────
  {
    slug: "chicken",
    name: "Κοτόπουλο",
    categorySlug: "white-meat",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ευέλικτο λευκό κρέας, μεσαίο σώμα — δεν έχει έντονη ιδιαιτερότητα ανά τρόπο ψησίματος (ψητό/σχάρας ενοποιήθηκαν).",
    seoTitle: "Κοτόπουλο & κρασί | Oenia",
    seoDescription: "Το κοτόπουλο ταιριάζει με ευέλικτα, μεσαίου σώματος κρασιά. Ανακάλυψε ελληνικές προτάσεις ταιριάσματος.",
  },
  {
    slug: "pork-tenderloin",
    name: "Χοιρινό φιλέτο",
    categorySlug: "white-meat",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Μεσαίου σώματος λευκό κρέας — ανοχή σε ελαφρώς off-dry κρασί.",
    seoTitle: "Χοιρινό φιλέτο & κρασί | Oenia",
    seoDescription: "Μεσαίου σώματος λευκό κρέας που αντέχει και ελαφρώς off-dry κρασιά. Δες τι ταιριάζει με χοιρινό φιλέτο.",
  },
  {
    slug: "duck",
    name: "Πάπια",
    categorySlug: "white-meat",
    saltiness: 2,
    fattiness: 4,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Πιο λιπαρό από κοτόπουλο — χρειάζεται οξύτητα ή τανίνη, με πραγματικό σώμα.",
    seoTitle: "Πάπια & κρασί | Oenia",
    seoDescription: "Η πάπια είναι πιο λιπαρή από το κοτόπουλο και θέλει κρασί με οξύτητα ή τανίνη. Δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "rabbit",
    name: "Κουνέλι",
    categorySlug: "white-meat",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Λευκό κρέας μεσαίου σώματος — ανοχή σε ελαφριές τανίνες.",
    seoTitle: "Κουνέλι & κρασί | Oenia",
    seoDescription: "Λευκό κρέας μεσαίου σώματος που ταιριάζει με ελαφριές τανίνες. Ανακάλυψε ποια ελληνικά κρασιά προτείνονται.",
  },

  // ── Ζυμαρικά & ριζότο (7) ─────────────────────────────────────────────
  {
    slug: "tomato-pasta",
    name: "Ζυμαρικά ντομάτα",
    categorySlug: "pasta",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Σάλτσα ντομάτας — χρειάζεται οξύτητα στο κρασί που να ταιριάξει με την οξύτητα της ντομάτας.",
    seoTitle: "Ζυμαρικά με ντομάτα & κρασί | Oenia",
    seoDescription: "Η σάλτσα ντομάτας θέλει κρασί με αντίστοιχη οξύτητα. Δες ποια ελληνικά κρασιά ταιριάζουν με ζυμαρικά ντομάτα.",
  },
  {
    slug: "carbonara",
    name: "Καρμπονάρα",
    categorySlug: "pasta",
    saltiness: 3,
    fattiness: 4,
    spiciness: 1,
    sweetness: 0,
    editorialSanityCheck: "Κρεμώδες, λιπαρό (αυγό/guanciale/τυρί) — η οξύτητα το ελαφραίνει, όχι η τανίνη.",
    seoTitle: "Καρμπονάρα & κρασί | Oenia",
    seoDescription: "Κρεμώδης, λιπαρή καρμπονάρα χρειάζεται κρασί με υψηλή οξύτητα. Ανακάλυψε ελληνικά λευκά που ταιριάζουν.",
  },
  {
    slug: "mushroom-risotto",
    name: "Ριζότο μανιταριών",
    categorySlug: "pasta",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Umami, κρεμώδες ριζότο — μεσαίο σώμα, χωρίς ανάγκη για έντονη οξύτητα.",
    seoTitle: "Ριζότο μανιταριών & κρασί | Oenia",
    seoDescription: "Το umami των μανιταριών ταιριάζει με μεσαίου σώματος κρασιά χωρίς έντονη οξύτητα. Δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "pesto-pasta",
    name: "Ζυμαρικά πέστο",
    categorySlug: "pasta",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Φρέσκο, βασιλικός/λάδι — χρειάζεται φρεσκάδα και οξύτητα, όχι βαρύ σώμα.",
    seoTitle: "Ζυμαρικά με πέστο & κρασί | Oenia",
    seoDescription: "Φρέσκο πέστο με βασιλικό θέλει κρασί με φρεσκάδα και οξύτητα. Ανακάλυψε τι ταιριάζει με ζυμαρικά πέστο.",
  },
  {
    slug: "pizza",
    name: "Πίτσα",
    categorySlug: "pasta",
    saltiness: 3,
    fattiness: 3,
    spiciness: 1,
    sweetness: 1,
    editorialSanityCheck: "Ντομάτα + τυρί + ποικίλα toppings — χρειάζεται οξύτητα και ευελιξία στο ταίριασμα.",
    seoTitle: "Πίτσα & κρασί | Oenia",
    seoDescription: "Ντομάτα, τυρί και διάφορα toppings ζητούν κρασί με οξύτητα και ευελιξία. Ανακάλυψε προτάσεις ταιριάσματος για πίτσα.",
  },
  {
    slug: "bolognese",
    name: "Μπολονέζ",
    categorySlug: "pasta",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Κιμάς σε σάλτσα ντομάτας — μεσαίο σώμα με πραγματική ανάγκη οξύτητας.",
    seoTitle: "Μπολονέζ & κρασί | Oenia",
    seoDescription: "Κιμάς σε σάλτσα ντομάτας θέλει κρασί μεσαίου σώματος με πραγματική οξύτητα. Δες τι ταιριάζει με μπολονέζ.",
  },

  // ── Τυριά & μεζέδες (4) ───────────────────────────────────────────────
  {
    slug: "feta",
    name: "Φέτα",
    categorySlug: "cheese",
    saltiness: 4,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Πολύ αλμυρό τυρί — χρειάζεται υψηλή οξύτητα στο κρασί.",
    seoTitle: "Φέτα & κρασί | Oenia",
    seoDescription: "Η αλμυρή φέτα ζητά κρασί με υψηλή οξύτητα. Ανακάλυψε ελληνικά λευκά που ταιριάζουν με φέτα.",
  },
  {
    slug: "graviera",
    name: "Γραβιέρα",
    categorySlug: "cheese",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ώριμο, σκληρό τυρί — μεσαίο σώμα, ανοχή σε ωριμότητα στο κρασί.",
    seoTitle: "Γραβιέρα & κρασί | Oenia",
    seoDescription: "Ώριμη, σκληρή γραβιέρα ταιριάζει με μεσαίου σώματος κρασιά που αντέχουν ωριμότητα. Δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "soft-fresh-cheese",
    name: "Φρέσκο τυρί",
    categorySlug: "cheese",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ελαφρύ, φρέσκο τυρί — φρεσκάδα, ελαφρύ σώμα, όχι βαριά δομή.",
    seoTitle: "Φρέσκο τυρί & κρασί | Oenia",
    seoDescription: "Ελαφρύ, φρέσκο τυρί θέλει κρασί με αντίστοιχη φρεσκάδα και ελαφρύ σώμα. Δες τι ταιριάζει.",
  },
  {
    slug: "blue-cheese",
    name: "Μπλε τυρί",
    categorySlug: "cheese",
    saltiness: 4,
    fattiness: 4,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Έντονο, αλμυρό/πικάντικο τυρί — χρειάζεται είτε γλυκύτητα είτε πολύ έντονη οξύτητα στο κρασί.",
    seoTitle: "Μπλε τυρί & κρασί | Oenia",
    seoDescription: "Έντονο μπλε τυρί ταιριάζει είτε με γλυκό είτε με πολύ όξινο κρασί. Ανακάλυψε ελληνικές προτάσεις ταιριάσματος.",
  },

  // ── Λαχανικά & vegetarian (6) ─────────────────────────────────────────
  {
    slug: "greek-salad",
    name: "Χωριάτικη σαλάτα",
    categorySlug: "vegetarian",
    saltiness: 3,
    fattiness: 2,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Φέτα + ελιές + λαχανικά — φρεσκάδα και οξύτητα.",
    seoTitle: "Χωριάτικη σαλάτα & κρασί | Oenia",
    seoDescription: "Φέτα, ελιές και λαχανικά θέλουν φρέσκο, όξινο κρασί. Δες ποια ελληνικά λευκά ταιριάζουν με χωριάτικη σαλάτα.",
  },
  {
    slug: "grilled-vegetables",
    name: "Ψητά λαχανικά",
    categorySlug: "vegetarian",
    saltiness: 1,
    fattiness: 1,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Ελαφριά, ψητά λαχανικά — ελαφρύ σώμα, φρεσκάδα.",
    seoTitle: "Ψητά λαχανικά & κρασί | Oenia",
    seoDescription: "Ελαφριά ψητά λαχανικά ταιριάζουν με κρασιά ελαφριού σώματος και φρεσκάδας. Ανακάλυψε προτάσεις ταιριάσματος.",
  },
  {
    slug: "stuffed-vegetables",
    name: "Γεμιστά",
    categorySlug: "vegetarian",
    saltiness: 2,
    fattiness: 2,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Ρύζι/κιμάς σε λαχανικά με λάδι — μεσαίο σώμα.",
    seoTitle: "Γεμιστά & κρασί | Oenia",
    seoDescription: "Ρύζι και κιμάς σε λαχανικά με λάδι θέλουν κρασί μεσαίου σώματος. Δες τι ταιριάζει με γεμιστά.",
  },
  {
    slug: "melitzanosalata",
    name: "Μελιτζανοσαλάτα",
    categorySlug: "vegetarian",
    saltiness: 2,
    fattiness: 3,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Λαδερή μελιτζανοσαλάτα — μεσαίο σώμα. (v2: ακονισμένο από το γενικό «eggplant-dishes» σε αυτό το συγκεκριμένο, πραγματικό πιάτο, ίδιες τιμές.)",
    seoTitle: "Μελιτζανοσαλάτα & κρασί | Oenia",
    seoDescription: "Λαδερή μελιτζανοσαλάτα ταιριάζει με κρασί μεσαίου σώματος. Ανακάλυψε ελληνικές προτάσεις ταιριάσματος.",
  },
  {
    slug: "fakes",
    name: "Φακές",
    categorySlug: "vegetarian",
    saltiness: 2,
    fattiness: 1,
    spiciness: 0,
    sweetness: 0,
    editorialSanityCheck: "Ελαφριά, λαδερή φακή — ελαφρύ σώμα. (v2: ακονισμένο από το γενικό «legumes» σε αυτό το συγκεκριμένο, πραγματικό πιάτο, ίδιες τιμές.)",
    seoTitle: "Φακές & κρασί | Oenia",
    seoDescription: "Η ελαφριά, λαδερή φακή ταιριάζει με κρασιά ελαφριού σώματος. Δες ποια ελληνικά κρασιά προτείνονται.",
  },
  {
    slug: "fava",
    name: "Φάβα",
    categorySlug: "vegetarian",
    saltiness: 2,
    fattiness: 1,
    spiciness: 0,
    sweetness: 1,
    editorialSanityCheck: "Λαδερή πουρέ φάβα — ελαφρύ σώμα, φρεσκάδα.",
    seoTitle: "Φάβα & κρασί | Oenia",
    seoDescription: "Η λαδερή πουρέ φάβα θέλει κρασί ελαφρύ και φρέσκο. Ανακάλυψε ποια ελληνικά κρασιά ταιριάζουν με φάβα.",
  },

  // ── Πικάντικο φαγητό (2) ──────────────────────────────────────────────
  {
    slug: "spicy-asian",
    name: "Πικάντικη ασιατική κουζίνα",
    categorySlug: "spicy",
    saltiness: 3,
    fattiness: 2,
    spiciness: 4,
    sweetness: 2,
    editorialSanityCheck: "Καυτερό, αρωματικό — χαμηλές τανίνες, ανοχή/ανάγκη για off-dry κρασί που τιθασεύει την καυτερότητα.",
    seoTitle: "Πικάντικη ασιατική κουζίνα & κρασί | Oenia",
    seoDescription: "Καυτερά, αρωματικά πιάτα ταιριάζουν με off-dry κρασιά χαμηλής τανίνης. Δες προτάσεις ταιριάσματος.",
  },
  {
    slug: "curry",
    name: "Κάρυ",
    categorySlug: "spicy",
    saltiness: 3,
    fattiness: 3,
    spiciness: 4,
    sweetness: 1,
    editorialSanityCheck: "Αρωματικό, καυτερό κάρυ — off-dry, αρωματικό κρασί, χαμηλή τανίνη.",
    seoTitle: "Κάρυ & κρασί | Oenia",
    seoDescription: "Το αρωματικό, καυτερό κάρυ ταιριάζει με off-dry κρασιά χαμηλής τανίνης. Ανακάλυψε τι προτείνεται.",
  },

  // ── Γλυκό / επιδόρπιο (5) ─────────────────────────────────────────────
  {
    slug: "chocolate-dessert",
    name: "Επιδόρπιο σοκολάτας",
    categorySlug: "dessert",
    saltiness: 0,
    fattiness: 3,
    spiciness: 0,
    sweetness: 5,
    editorialSanityCheck: "Έντονα γλυκό επιδόρπιο — απαιτεί κρασί τουλάχιστον εξίσου γλυκό, αλλιώς φαίνεται ξινό/λεπτό στη σύγκριση.",
    seoTitle: "Επιδόρπιο σοκολάτας & κρασί | Oenia",
    seoDescription: "Έντονα γλυκό επιδόρπιο θέλει εξίσου γλυκό κρασί. Δες ποια ελληνικά γλυκά κρασιά ταιριάζουν με σοκολάτα.",
  },
  {
    slug: "fruit-dessert",
    name: "Επιδόρπιο φρούτων",
    categorySlug: "dessert",
    saltiness: 0,
    fattiness: 1,
    spiciness: 0,
    sweetness: 4,
    editorialSanityCheck: "Γλυκό αλλά πιο ελαφρύ από σοκολάτα — γλυκό κρασί με φρεσκάδα.",
    seoTitle: "Επιδόρπιο φρούτων & κρασί | Oenia",
    seoDescription: "Ελαφρύ, φρουτώδες επιδόρπιο ταιριάζει με γλυκό κρασί που έχει φρεσκάδα. Ανακάλυψε προτάσεις ταιριάσματος.",
  },
  {
    slug: "baklava",
    name: "Μπακλαβάς",
    categorySlug: "dessert",
    saltiness: 0,
    fattiness: 3,
    spiciness: 1,
    sweetness: 5,
    editorialSanityCheck: "Πολύ γλυκό, με μπαχαρικά — χρειάζεται πολύ γλυκό κρασί.",
    seoTitle: "Μπακλαβάς & κρασί | Oenia",
    seoDescription: "Ο πολύ γλυκός μπακλαβάς με μπαχαρικά θέλει εξίσου γλυκό κρασί. Δες ποια ελληνικά κρασιά ταιριάζουν.",
  },
  {
    slug: "cheesecake",
    name: "Cheesecake",
    categorySlug: "dessert",
    saltiness: 1,
    fattiness: 4,
    spiciness: 0,
    sweetness: 4,
    editorialSanityCheck: "Γλυκό, κρεμώδες, με λίγη οξύτητα από το τυρί — γλυκό κρασί με πραγματική οξύτητα.",
    seoTitle: "Cheesecake & κρασί | Oenia",
    seoDescription: "Κρεμώδες cheesecake με λίγη οξύτητα ταιριάζει με γλυκό κρασί που έχει αντίστοιχη φρεσκάδα. Δες προτάσεις.",
  },
  {
    slug: "ice-cream",
    name: "Παγωτό",
    categorySlug: "dessert",
    saltiness: 0,
    fattiness: 3,
    spiciness: 0,
    sweetness: 4,
    editorialSanityCheck: "Γλυκό, κρύο, κρεμώδες — γλυκό κρασί.",
    seoTitle: "Παγωτό & κρασί | Oenia",
    seoDescription: "Κρύο, κρεμώδες παγωτό ταιριάζει με γλυκά ελληνικά κρασιά. Ανακάλυψε ποια προτείνονται.",
  },

  // ── Επιπλέον εγκεκριμένο entry (εκτός των 44, βλ. σημείωση παραπάνω) ──
  {
    slug: "bakaliaros-skordalia",
    name: "Μπακαλιάρος σκορδαλιά",
    categorySlug: "seafood",
    saltiness: 4,
    fattiness: 4,
    spiciness: 1,
    sweetness: 0,
    editorialSanityCheck:
      "Παστό, τηγανητό ψάρι με πικάντικη σκορδαλιά σκόρδου· χρειάζεται κρασί με έντονη οξύτητα ώστε να ισορροπήσει το αλάτι του παστώματος και το λίπος του τηγανίσματος.",
    seoTitle: "Μπακαλιάρος σκορδαλιά & κρασί | Oenia",
    seoDescription: "Παστός, τηγανητός μπακαλιάρος με σκορδαλιά θέλει κρασί υψηλής οξύτητας. Δες ποια ελληνικά λευκά ταιριάζουν.",
  },
];

// Οι umbrella έννοιες του Taxonomy v2 (Level 1.5) — ΔΕΝ έχουν numeric
// profile, ΔΕΝ μπαίνουν ποτέ στο FOOD_PROFILES array, χρησιμεύουν μόνο ως
// τεκμηρίωση/regression-guard ότι κανένα umbrella δεν έγινε ποτέ scorer input.
export const UMBRELLA_ONLY_SLUGS = ["game-meat", "cured-meats", "mezedes-mix"] as const;

// Slugs των 44 εγκεκριμένων Taxonomy v2 dishes (χωρίς το bakaliaros-skordalia,
// που εγκρίθηκε ξεχωριστά, αργότερα, ως πρόσθετο entry).
export const TAXONOMY_V2_DISH_SLUGS = FOOD_PROFILES.filter((d) => d.slug !== "bakaliaros-skordalia").map(
  (d) => d.slug
);

// Backward-compatible subset για τα 6 critical test dishes (ήδη σε χρήση από
// scoreWineForDish.test.ts και το DB validation script).
const CRITICAL_SLUGS = ["sushi", "steak", "carbonara", "moussaka", "chocolate-dessert", "bakaliaros-skordalia"];
export const CRITICAL_FOOD_PROFILES: FoodProfile[] = FOOD_PROFILES.filter((d) => CRITICAL_SLUGS.includes(d.slug));
